name: .NET Core

on:
  push:
    branches: [ master, cicd ]
  pull_request:
    branches: [ master, cicd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Package
      run: dotnet pack -c Release -o nuget-packages 
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: nuget-packages
        path: nuget-packages
    - name: Push
      run: dotnet nuget push ./nuget-packages/*.nupkg --skip-duplicate --no-symbols true